# 服务端口
server:
  port: 80
# 服务名
spring:
  application:
    name: gatway
# nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
  #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      #设置路由id
      routes[0]:
        id: service-user
        #设置路由的uri
        uri: lb://service-user
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates: Path=/user/**
      #设置路由id
      routes[1]:
        id: message
        #设置路由的uri
        uri: lb://message
        predicates: Path=/test/**
  redis:
    host: 127.0.0.1
    port: 6379
    database:  0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
  #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
#  #设置路由id
#spring.cloud.gateway.routes[1].id=service-cmn
#  #设置路由的uri
#spring.cloud.gateway.routes[1].uri=lb://service-cmn
#  #设置路由断言,代理servicerId为auth-service的/auth/路径
#spring.cloud.gateway.routes[1].predicates= Path=/*/cmn/**
#
#
#  #设置路由id
#spring.cloud.gateway.routes[2].id=service-user
#  #设置路由的uri
#spring.cloud.gateway.routes[2].uri=lb://service-user
#  #设置路由断言,代理servicerId为auth-service的/auth/路径
#spring.cloud.gateway.routes[2].predicates= Path=/*/user/**
#
#
#  #设置路由id
#spring.cloud.gateway.routes[3].id=service-msm
#  #设置路由的uri
#spring.cloud.gateway.routes[3].uri=lb://service-msm
#  #设置路由断言,代理servicerId为auth-service的/auth/路径
#spring.cloud.gateway.routes[3].predicates= Path=/*/msm/**
#
#
#  #设置路由id
#spring.cloud.gateway.routes[4].id=service-user
#  #设置路由的uri
#spring.cloud.gateway.routes[4].uri=lb://service-user
#  #设置路由断言,代理servicerId为auth-service的/auth/路径
#spring.cloud.gateway.routes[4].predicates= Path=/*/ucenter/**
#
#
#  #设置路由id
#spring.cloud.gateway.routes[5].id=service-oss
#  #设置路由的uri
#spring.cloud.gateway.routes[5].uri=lb://service-oss
#  #设置路由断言,代理servicerId为auth-service的/auth/路径
#spring.cloud.gateway.routes[5].predicates= Path=/*/oss/**
#
#
#  #设置路由id
#spring.cloud.gateway.routes[6].id=service-order
#  #设置路由的uri
#spring.cloud.gateway.routes[6].uri=lb://service-order
#  #设置路由断言,代理servicerId为auth-service的/auth/路径
#spring.cloud.gateway.routes[6].predicates= Path=/*/order/**
#
#
#  #设置路由id
#spring.cloud.gateway.routes[7].id=service-statistics
#  #设置路由的uri
#spring.cloud.gateway.routes[7].uri=lb://service-statistics
#  #设置路由断言,代理servicerId为auth-service的/auth/路径
#spring.cloud.gateway.routes[7].predicates= Path=/*/statistics/**

