# 服务端口
server:
  port: 8160
  # 服务名
spring:
  application:
    name: service-user
  # 环境设置：dev、test、prod
  #spring.main.allow-bean-definition-overriding=true
# mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  #spring.datasource.url=jdbc:mysql://192.168.44.163:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/yygh_user?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
#返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database:  0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
  #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/study/service/user/mapper/xml/*.xml
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.study.service.user.mapper: debug
  file: /log/myspringclound.log
#微信配置信息
wx:
  open:
    app_id: xxx
    app_secret: xxx
    redirect_url: xxxxx

RSA:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCsUGnOWyYluS1MENY1MjDaymXqhWdzqdSLqhc5GWHUB6tsejyWVpJf4yFCI5+DQPagQc/ldocLoesq6d710NPuLnF24rYoxnddZ/ZZehEKS7VGUDUG6GKw2f9JSl3WEkbc0cOSatl5msuykPY9C+BRRHyeaRuMNdANDgTqaH1kdQIDAQAB
  privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKxQac5bJiW5LUwQ1jUyMNrKZeqFZ3Op1IuqFzkZYdQHq2x6PJZWkl/jIUIjn4NA9qBBz+V2hwuh6yrp3vXQ0+4ucXbitijGd11n9ll6EQpLtUZQNQboYrDZ/0lKXdYSRtzRw5Jq2Xmay7KQ9j0L4FFEfJ5pG4w10A0OBOpofWR1AgMBAAECgYEAlJO9t7X2XZ6fBTCbU0EUyQKuABrJSf0NDOQ7o/tT1BxM3ntD1KmPCujwW3QV7XnNbf9xQD0EUq5p9RW1LyXCJfgVAUzc1jDgzEhxJS4CHY1aVoTRtAL0rcTEbZbUHgXpbn7S7XEk8SWQRvZeb+JzcLYwkxv9sUMrcziF4FcqYl0CQQDrOYAGjkrZM8w4HDMiXeuk4YviTGZod0vMs19q0yPx0EJN/CXQoGvi07wUsA8etu1k7mgAYmIGv3h8mjmNW3szAkEAu4h8396y1PISW14ok0aTrx9ZCGFWFlo6hRkguW4bJskUWaZ4UBQ6+mOlAFxisyelLtxd+UaFZYUK02rlM+5htwJBALGdU2yf2Si1Egl0UbArlxmDLasM4W8UVWoWL4BsOgIHrWlRcgRcfdpi4uwEHQamPg8ubd2MbFSIE6SSl86DOz0CQEGjAeHxNjJmD5q/GACEIUiX9jeCqfjk17qiEtwT95jZpC/EnjOZAROGMMgxjbIa3CvMoW+QCTyBFkrtDQ/iDX0CQQDlII2VmgO6CIklJogOxKCqAaPzid/iM57uCJkAO6Sx8nrof6c2ZCnAcITlvRAT4UjDqB8fFTX+csTnR1ecMbB2

service:
  baseUrl: http://localhost:3000
